<?php

namespace Colzak\EventBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends DocumentRepository
{
    public function getNextGame() {
    	//531052e0d8291bca078b4568
        return $this->createQueryBuilder('Game')
            ->where("function() { return this.id == '531052e0d8291bca078b4568' && this.date >= new Date(); }")
            ->sort('date', 'asc')
            ->getQuery()
            ->getSingleResult();
    }

    public function getByDate() {
    	return $this->createQueryBuilder('Game')
            ->sort('date', 'desc')
            ->getQuery()
            ->execute();
    }
}