<?php

namespace Colzak\EventBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends DocumentRepository
{
}