colzak_admin:
    resource: "@ColzakAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

colzak_user:
    resource: "@ColzakUserBundle/Resources/config/routing.yml"
    prefix:   /

colzak_blog:
    resource: "@ColzakBlogBundle/Resources/config/routing.yml"
    prefix:   /

colzak_home:
    resource: "@ColzakHomeBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"