<?php

namespace Colzak\BlogBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends DocumentRepository
{
    public function getLastArticles($limit = 5) {
        return $this->createQueryBuilder('Article')
            ->select('id', 'title', 'content', 'filePath')
            ->sort('createdAt', 'desc')
            ->limit($limit)
            ->getQuery()
            ->execute();
    }
}