colzak_blog_articles:
    pattern:  /articles
    defaults: { _controller: ColzakBlogBundle:Article:articles }

colzak_blog_media:
    pattern:  /media
    defaults: { _controller: ColzakBlogBundle:Article:media }

colzak_blog_pages:
    pattern:  /page/{name}
    defaults: { _controller: ColzakBlogBundle:Article:loadPage}
