# _clzk_article:
#     resource: "@ColzakBlogBundle/Controller/ArticleAPIController.php"
#     type:     rest

colzak_blog_articles:
    pattern:  /articles
    defaults: { _controller: ColzakBlogBundle:Article:articles }

colzak_blog_media:
    pattern:  /media
    defaults: { _controller: ColzakBlogBundle:Media:listAlbum }

colzak_blog_pages:
    pattern:  /page/{url}
    defaults: { _controller: ColzakBlogBundle:Article:loadPage}

colzak_blog_article:
    pattern:  /article/{url}
    defaults: { _controller: ColzakBlogBundle:Article:view}
